sudo: required

language: php

services:
  - docker

install:
  - docker build -t hub.ovn.io/busybox:travis .
  - docker run -d -p 127.0.0.1:80:80 --name webserver hub.ovn.io/busybox:travis /bin/sh -c "composer selfupdate; composer install"

after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.ovn.io;
    docker push hub.ovn.io/busybox:travis;
    fi

script:
  - docker ps -a

notifications:
  email:
    - k@yejune.com