sudo: required

language: php

dist: xenial

servies:
  - docker

php:
  - 7.0

env:
  global:
    - DOCKER_HUB=hub.ovn.io
    - DOCKER_REPO_SLUG=websrv
    - DOCKER_REPO="$DOCKER_HUB/$DOCKER_REPO_SLUG"
    - if [ ! -z "$TRAVIS_TAG" ]; then
        export IMAGE_TAG="$TRAVIS_TAG$TRAVIS_BUILD_NUMBER";
      fi
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "release" ]; then
        export IMAGE_TAG="$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER";
      fi

before_install:
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq docker-ce

install:
  - function dockin() { sudo docker exec -it travis /bin/sh -c "$@"; }

script:
  - sudo docker build --tag travis .;
  - sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/var/www --name travis travis;
  - dockin "composer self-update";
  - dockin "composer install";
  - dockin "apt-get update -y -qq";
  - dockin "apt-get install -y -qq curl docker-ce";
  - dockin "docker build --tag $DOCKER_REPO_SLUG .";

after_success:
  - dockin "docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG";
  - dockin "docker login -u$DOCKER_USERNAME -p$DOCKER_PASSWORD $DOCKER_HUB";
  - dockin "docker push $DOCKER_REPO:$IMAGE_TAG";
  - dockin docker logout $DOCKER_HUB;
  - echo "Done. $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG";

notifications:
  email:
    recipients:
      - k@yejune.com
