sudo: required

language: php

php:
  - 7.0

services:
  - docker

env:
  global:
    - DOCKER_REPOSITORY=hub.ovn.io/websrv

#install:
#  -

script:
  - env
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ $TRAVIS_BRANCH == "develop" ] || [ $TRAVIS_BRANCH == "release" ]; then
    export IMAGE_TAG=$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER
    docker build --build-arg BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -t $DOCKER_REPOSITORY:$IMAGE_TAG .;
    fi
  - if [ ! -z "$TRAVIS_TAG" ]; then
    export IMAGE_TAG=$TRAVIS_TAG$TRAVIS_BUILD_NUMBER
    docker build --build-arg BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -t $DOCKER_REPOSITORY:$IMAGE_TAG .;
    fi
  - if [ ! -z "$IMAGE_TAG" ]; then
    docker run -d -p 127.0.0.1:80:80 --name webserver $DOCKER_REPOSITORY:$IMAGE_TAG /bin/sh -c "composer self-update; composer install"
    fi

after_success:
  - docker ps -a

before_deploy:
  - if [ ! -z "$IMAGE_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPOSITORY:$IMAGE_TAG;
    docker logout;
    else
    fi
  - exit 1;


notifications:
  email:
    recipients:
      - k@yejune.com
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "$DOCKER_REPOSITORY:%{branch}:%{build_number}"