sudo: required

language: php

dist: xenial

servies:
  - docker

php:
  - 7.0

addons:
 apt:
  packages:
    - libyaml-dev

env:
  global:
    - DOCKER_HUB=hub.ovn.io
    - DOCKER_REPO_SLUG=websrv
    - DOCKER_REPO="$DOCKER_HUB/$DOCKER_REPO_SLUG"
  matrix:
    - PHALCON_VERSION="v3.0.4"

install:
  - sudo apt-get update -y
  - curl -s https://get.docker.com | sudo sh

script:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      export IMAGE_TAG="$TRAVIS_TAG$TRAVIS_BUILD_NUMBER";
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "release" ]; then
      export IMAGE_TAG="$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER";
    fi

  - sudo docker build --tag travis .;
  - sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/var/www --name travis travis;
  - sudo docker exec -it travis /bin/sh -c "composer self-update";
  - sudo docker exec -it travis /bin/sh -c "composer install";
  - sudo docker exec -it travis /bin/sh -c "apt-get update -y";
  - sudo docker exec -it travis /bin/sh -c "apt-get install -y curl iputils-ping";
  - sudo docker exec -it travis /bin/sh -c "curl -s https://get.docker.com | sh";
  - sudo docker exec -it webserver /bin/sh -c "docker build --tag $DOCKER_REPO_SLUG .";
  - sudo docker exec -it webserver /bin/sh -c "docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG";
  - sudo docker exec -it webserver /bin/sh -c "docker login -u$DOCKER_USERNAME -p$DOCKER_PASSWORD $DOCKER_HUB";
  - sudo docker exec -it webserver /bin/sh -c "docker push $DOCKER_REPO:$IMAGE_TAG";

after_success:
  - docker ps -a
  - if [ ! -z "$IMAGE_TAG1" ]; then
      sudo docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG;
      sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_HUB;
      sudo docker push $DOCKER_REPO:$IMAGE_TAG;
      echo "success docker push $DOCKER_REPO:$IMAGE_TAG";
      sudo docker logout $DOCKER_HUB;
    fi

notifications:
  email:
    recipients:
      - k@yejune.com
