sudo: required

language: php

dist: xenial

servies:
  - docker

php:
  - 7.0

addons:
 apt:
  packages:
    - libyaml-dev

env:
  global:
    - DOCKER_HUB=hub.ovn.io
    - DOCKER_REPO_SLUG=websrv
    - DOCKER_REPO="$DOCKER_HUB/$DOCKER_REPO_SLUG"
    - if [ ! -z "$TRAVIS_TAG" ]; then
        export IMAGE_TAG="$TRAVIS_TAG$TRAVIS_BUILD_NUMBER";
      fi
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "release" ]; then
        export IMAGE_TAG="$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER";
      fi

install:
  - sudo apt-get update -y
  - curl -s https://get.docker.com | sudo sh

script:
  - sudo docker build --tag travis .;
  - sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/var/www --name travis travis;
  - sudo docker exec -it travis /bin/sh -c "composer self-update";
  - sudo docker exec -it travis /bin/sh -c "composer install";
  - sudo docker exec -it travis /bin/sh -c "apt-get update -y";
  - sudo docker exec -it travis /bin/sh -c "apt-get install -y curl";
  - sudo docker exec -it travis /bin/sh -c "curl -s https://get.docker.com | sh";
  - sudo docker exec -it travis /bin/sh -c "docker build --tag $DOCKER_REPO_SLUG .";

after_success:
  - sudo docker exec -it travis /bin/sh -c "docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG";
  - sudo docker exec -it travis /bin/sh -c "docker login -u$DOCKER_USERNAME -p$DOCKER_PASSWORD $DOCKER_HUB";
  - sudo docker exec -it travis /bin/sh -c "docker push $DOCKER_REPO:$IMAGE_TAG";
  - function test() { sudo docker exec -it travis /bin/sh -c  "$@"; }
  - test "docker logout $DOCKER_HUB";

notifications:
  email:
    recipients:
      - k@yejune.com
