sudo: required

language: php

php:
  - 7.0

services:
  - docker

env:
  global:
    - DOCKER_REPO_SLUG=websrv
    - DOCKER_REPO=hub.ovn.io/websrv
#install:
#  -

script:
  - docker build -t $DOCKER_REPO_SLUG .

  - if [ ! -z "$TRAVIS_TAG" ]; then
      #export IMAGE_TAG=$TRAVIS_TAG;
      export IMAGE_TAG="$TRAVIS_TAG$TRAVIS_BUILD_NUMBER"
    fi

  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "release" ]; then
      #export IMAGE_TAG=$TRAVIS_BRANCH;
      export IMAGE_TAG="$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER"
    fi

  - if [ ! -z "$IMAGE_TAG" ]; then
      docker run -d -p 127.0.0.1:80:80 --name webserver $DOCKER_REPO_SLUG /bin/sh -c "composer self-update; composer install";
    fi

after_success:
  - docker ps -a

before_deploy:
  - if [ ! -z "$IMAGE_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG
      docker push $DOCKER_REPO:$IMAGE_TAG;
      docker logout;
    else
    fi


notifications:
  email:
    recipients:
      - k@yejune.com
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "$DOCKER_REPO:%{branch}:%{build_number}"