sudo: required

language: php

dist: xenial

services:
  - docker

php:
  - 7.0

env:
  global:
    - DOCKER_HUB=hub.ovn.io
    - DOCKER_REPO_SLUG=websrv
    - DOCKER_REPO="$DOCKER_HUB/$DOCKER_REPO_SLUG"
    - if [ ! -z "$TRAVIS_TAG" ]; then
        export IMAGE_TAG="$TRAVIS_TAG$TRAVIS_BUILD_NUMBER";
        export IMAGE_TAGNAME="$TRAVIS_TAG/$TRAVIS_BUILD_NUMBER";
      else
        export IMAGE_TAG="$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER";
        export IMAGE_TAGNAME="$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER";
      fi

branches:
  # blocklist
  except:
    - master
    - except
  # safelist
  only:
    - develop
    - release
    - /^deploy-.*$/

before_install:
  - sudo apt-get update -y
  - sudo apt-get remove docker-engine -y
  - curl -s https://get.docker.com | sudo sh
  - sudo usermod -aG docker $USER

install:
  - function dockin() { docker exec -it travis /bin/sh -c "$@"; }

before_script:
  - which docker
  - export SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - export DOCKER_LABEL_NAME=`echo $TRAVIS_REPO_SLUG | sed 's/\//\./g'`
  - echo "SHORT_COMMIT  $SHORT_COMMIT"
  - echo "DOCKER_LABEL_NAME  $DOCKER_LABEL_NAME"
  - echo "TRAVIS_COMMIT  $TRAVIS_COMMIT"
  - echo "TRAVIS_TAG  $TRAVIS_TAG"
  - echo "TRAVIS_BRANCH  $TRAVIS_BRANCH"
  - echo "TRAVIS_BUILD_NUMBER  $TRAVIS_BUILD_NUMBER"
  - echo "TRAVIS_REPO_SLUG  $TRAVIS_REPO_SLUG"

script:
  - docker build --tag travis .;
  - docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/var/www --name travis travis;
  - dockin "apt-get update -y";
  - dockin "apt-get install -y curl";
  - dockin "curl -s https://get.docker.com | sh";
  - dockin "composer self-update";
  - dockin "composer install";
  - dockin "docker build --tag $DOCKER_REPO_SLUG .";

xafter_success:
  - dockin "docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG";

#before_deploy:
after_success:
  - mkdir -p build
  - cd build
  - docker save $DOCKER_REPO_SLUG | gzip -c > docker_image.tgz
  - zip -r build.zip docker_image.tgz appspec.yml deploy || true
  - cd ..
  - mkdir -p upload
  - mv build/build.zip upload

deploy:
  - provider: s3
    access_key_id: AKIAIYFMU73S3HMTZRVA
    secret_access_key: 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
    bucket: yejune-deploy
    region: ap-northeast-2
    local_dir: upload
    upload-dir: $TRAVIS_REPO_SLUG/latest/$TRAVIS_BRANCH
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: $TRAVIS_REPO_SLUG
      all_branches: true
  - provider: codedeploy
    access_key_id: AKIAIYFMU73S3HMTZRVA
    secret_access_key: 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
    bucket: yejune-deploy
    key: $TRAVIS_REPO_SLUG/latest/$IMAGE_TAGNAME/build.zip
    bundle_type: zip
    application: app
    deployment_group: deploy
    region: ap-northeast-2
    on:
      repo: $TRAVIS_REPO_SLUG
      all_branches: true

notifications:
  email:
    recipients:
      - k@yejune.com
