sudo: required

language: php

dist: xenial

php:
  - 7.0

env:
  global:
    - DOCKER_HUB=hub.ovn.io
    - DOCKER_REPO_SLUG=websrv
    - DOCKER_REPO="$DOCKER_HUB/$DOCKER_REPO_SLUG"
  matrix:
    - PHALCON_VERSION="v3.0.4"

install:
  - sudo apt-get update -y
  - curl -s https://get.docker.com | sudo sh
  - composer self-update
  - git clone --depth=1 -q --branch=${PHALCON_VERSION} https://github.com/phalcon/cphalcon.git
  - '(cd cphalcon/build; bash install &> /dev/null && cd ../..;)'
  - '(echo "extension=phalcon.so" > ./phalcon.ini && phpenv config-add ./phalcon.ini &> /dev/null)'
  - php --ri phalcon

script:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      export IMAGE_TAG="$TRAVIS_TAG$TRAVIS_BUILD_NUMBER";
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "release" ]; then
      export IMAGE_TAG="$TRAVIS_BRANCH$TRAVIS_BUILD_NUMBER";
    fi
  - if [ ! -z "$IMAGE_TAG" ]; then
      composer install;
      sudo docker build --tag $DOCKER_REPO_SLUG .;
      sudo docker run -d -p 127.0.0.1:80:80 --name webserver $DOCKER_REPO_SLUG;
    fi

after_success:
  - docker ps -a
  - if [ ! -z "$IMAGE_TAG" ]; then
      sudo docker tag $DOCKER_REPO_SLUG $DOCKER_REPO:$IMAGE_TAG;
      sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_HUB;
      sudo docker push $DOCKER_REPO:$IMAGE_TAG;
      echo "success docker push $DOCKER_REPO:$IMAGE_TAG";
      sudo docker logout $DOCKER_HUB;
    fi

notifications:
  email:
    recipients:
      - k@yejune.com
